export const estilosApp = {
  layout: {
    minHeight: "100vh",
    backgroundColor: "#F7F8FA",
    display: "flex",
    flexDirection: "column",
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  main: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem",
  },
};

export const estilosNav = {
  nav: {
    display: "flex",
    gap: "0.5rem",
    padding: "1rem 1.5rem",
    backgroundColor: "#ffffff",
    borderBottom: "1px solid #E5E7EB",
  },
  boton: {
    padding: "0.5rem 1rem",
    border: "1px solid #D1D5DB",
    borderRadius: "6px",
    backgroundColor: "#ffffff",
    color: "#374151",
    fontSize: "0.875rem",
    fontFamily: "inherit",
    fontWeight: 600,
    cursor: "pointer",
  },
  botonActivo: {
    padding: "0.5rem 1rem",
    border: "1px solid #1E3A8A",
    borderRadius: "6px",
    backgroundColor: "#1E3A8A",
    color: "#ffffff",
    fontSize: "0.875rem",
    fontFamily: "inherit",
    fontWeight: 600,
    cursor: "pointer",
  },
};

export const estilosTarjeta = {
  tarjeta: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.06)",
    width: "100%",
    maxWidth: "480px",
    overflow: "hidden",
  },
  encabezado: {
    display: "flex",
    alignItems: "stretch",
    gap: "1.25rem",
    padding: "1.5rem 1.75rem",
    borderBottom: "1px solid #E5E7EB",
  },
  barraLateral: {
    width: "4px",
    borderRadius: "4px",
    backgroundColor: "#1E3A8A",
    flexShrink: 0,
  },
  eyebrow: {
    margin: 0,
    fontSize: "0.7rem",
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#6B7280",
  },
  titulo: {
    margin: "0.2rem 0 0",
    fontSize: "1.1rem",
    fontWeight: 700,
    color: "#111827",
  },
  form: {
    padding: "1.75rem",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  campo: {
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
  },
  label: {
    fontSize: "0.8rem",
    fontWeight: 600,
    color: "#374151",
    letterSpacing: "0.01em",
  },
  control: {
    padding: "0.5rem 0.75rem",
    fontSize: "0.9rem",
    border: "1px solid #D1D5DB",
    borderRadius: "6px",
    backgroundColor: "#F9FAFB",
    color: "#111827",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  feedbackExito: {
    padding: "0.75rem 1rem",
    backgroundColor: "#F0FDF4",
    border: "1px solid #86EFAC",
    borderRadius: "6px",
    color: "#15803D",
    fontSize: "0.875rem",
    fontWeight: 500,
  },
  feedbackError: {
    padding: "0.75rem 1rem",
    backgroundColor: "#FEF2F2",
    border: "1px solid #FECACA",
    borderRadius: "6px",
    color: "#DC2626",
    fontSize: "0.875rem",
    fontWeight: 500,
  },
  boton: {
    marginTop: "0.25rem",
    padding: "0.65rem 1.25rem",
    backgroundColor: "#1E3A8A",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  botonDeshabilitado: {
    marginTop: "0.25rem",
    padding: "0.65rem 1.25rem",
    backgroundColor: "#9CA3AF",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "not-allowed",
  },
};
